### ISSUE TITLE
Uncaught TypeError: Illegal invocation in Chrome

### ISSUE THREAD

**Issue by yunyu** [feross/queue-microtask#10]
When using this library in Chrome with a bundler, I get an `Uncaught TypeError: Illegal invocation` when running it. You can replicate this without the library by assigning queueMicrotask to a field in an object in the Chrome console:

![image](https://user-images.githubusercontent.com/8008350/94841658-5c412000-03e8-11eb-9c2d-c4ad3a8fa83b.png)

queueMicrotask should be bound to `window` if present. This is not an issue in Node.

**Comment by feross** [comment]
Fixed in #11
