### ISSUE TITLE
Not compatible with strict mode

### ISSUE THREAD

**Issue by yunyu** [feross/queue-microtask#12]
This package doesn't work when used with a bundler that enforces strict mode – switching to typeof globalThis.queueMicrotask would fix it

**Comment by feross** [comment]
I am confused by this issue. `typeof queueMicrotask === 'function'` is perfectly valid code in strict mode. Please post an minimal example that reproduces your error.

**Comment by yunyu** [comment]
@feross Here's an example: https://stackoverflow.com/questions/31540765/variable-typeof-object-in-strict-mode

I don't currently have access to a browser environment that triggers this, but I saw this exception reported via Sentry in an older version of Safari. If `queueMicrotask` doesn't exist, then `typeof queueMicrotask` is invalid in strict mode.

**Comment by feross** [comment]
The accepted answer on StackOverflow makes no sense. You can always do `typeof queueMicrotask` – even in strict mode. This is how JavaScript works. If an old version of Safari is triggering a warning, then it's buggy behavior in Safari.
