### ISSUE TITLE
globalThis

### ISSUE THREAD

**Issue by avasuro** [feross/queue-microtask#13]
Because of 92b2739daa7be346e27db4eba5ddc9b8f1a985e7 (where you refactored code to use globalThis) support of node versions older than v12 where dropped (because older node versions doesn't have support of globalThis), which is a breaking change, so you should either:

- Update major version of your package instead of updating minor version (should be 2.0.0 instead of 1.2.0) and remove version 1.2.0 and 1.2.1 from npm repository
- Do not use globalThis

If you will not do that a lot of packages that has your package as dependency will fail. I faced this issue right now.
Could you please fix this. Thank you :)

**Comment by feross** [comment]
What version of Node.js is this failing on for you?

I just tested with v6.17.1, v8.16.2, v10.18.0, and v10.23.0 and the test suite passed on all of them.

**Comment by avasuro** [comment]
@feross 11.15.0

I think something wrong in test suites, because even according to [this table](https://node.green/#ES2020-features-globalThis) globalThis is not supported on old node versions, so there is no way how globalThis can work.

P.S. I pulled this repo and did `npm run test` - test is failing with "ReferenceError: globalThis is not defined"
P.P.S. Indeed, on node 10.23.0 test is passing :) So this issue relates to v11 only. I know why - because in this version native queueMicrotask was first time added (so in all previous versions line number 5 never executed, that's why tests are passing in node v10 and less).

**Comment by feross** [comment]
Ah, I see. Basically, Node 11 is in the unlucky situation of supporting `queueMicrotask` but not supporting `globalThis`. But all stable versions of Node.js either support one or the other.

I'm going to close this since Node 11 is not a supported version.

**Comment by jindrahm** [comment]
@feross When you break backward compatibility you should change the major version, see https://docs.npmjs.com/about-semantic-versioning. So could you please revert that breaking commit, release new patch.. and than you can put that back and do major release.
