### ISSUE TITLE
"ExperimentalWarning: queueMicrotask() is experimental" Node 11

### ISSUE THREAD

**Issue by tinchoz49** [feross/queue-microtask#5]
Hi @feross how are you?

We are using Node 11 in some of our projects and we start to see a warning message with the update of simple-peer: `ExperimentalWarning: queueMicrotask() is experimental`

Do you think it's ok if I do a PR to use the fallback in Node 11 too?

**Comment by feross** [comment]
Node 11 is [unsupported](https://nodejs.org/en/about/releases/) and the warning is not present in Node 12. I'd rather not add additional code to this package just to support an outdated version of Node.

Is it possible for you to update to Node 12?
