### ISSUE TITLE
Accept function arguments?

### ISSUE THREAD

**Issue by aarong** [feross/queue-microtask#9]
I realize that this would be a deviation from the standard, but any interest in accepting arguments to be passed to the callback? For example...

`queueMicrotask(myFunction, something) // Calls myFunction(something) as a microtask`

This functionality is available with setTimeout/setImmediate  and can help make code more readable.

I'm happy to submit a PR, just let me know.

**Comment by feross** [comment]
Hey, thanks for the suggestion! The goal of this package is to match the standard so I don't want to add non-standard additions like this.
